<a href="https://colab.research.google.com/github/Hjhirp/Language-Model-Implementation/blob/main/Notebook/Language_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Language model

In [ ]:
from tensorflow import keras
import numpy
from numpy import array
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences

In [ ]:
data = """ Jack and Jill went up the hill .\n To fetch a pail of water .\n Jack fell down and broke his crown .\n And Jill came tumbling after ."""
print("Data:", data, type(data))


Data:  Jack and Jill went up the hill .
 To fetch a pail of water .
 Jack fell down and broke his crown .
 And Jill came tumbling after . <class 'str'>


In [ ]:
data_splitted=data.split('\n') #returns a list of strings
print("Data_Splitted:", data_splitted, type(data_splitted))

Data_Splitted: [' Jack and Jill went up the hill .', ' To fetch a pail of water .', ' Jack fell down and broke his crown .', ' And Jill came tumbling after .'] <class 'list'>


In [ ]:
tokenizer=Tokenizer(filters='!"#$%&()*+,-/:;<=>?@[\]^_`{|}~')

In [ ]:
tokenizer.fit_on_texts(data_splitted) #learns a vocabulary
print("Word Indices:", tokenizer.word_index) #tokenizer.word_index is a dictionary


Word Indices: {'.': 1, 'and': 2, 'jack': 3, 'jill': 4, 'went': 5, 'up': 6, 'the': 7, 'hill': 8, 'to': 9, 'fetch': 10, 'a': 11, 'pail': 12, 'of': 13, 'water': 14, 'fell': 15, 'down': 16, 'broke': 17, 'his': 18, 'crown': 19, 'came': 20, 'tumbling': 21, 'after': 22}


In [ ]:
vocab_size = len(tokenizer.word_index) + 1
print("Vocab Size:", vocab_size)


Vocab Size: 23


In [ ]:
sequences=tokenizer.texts_to_sequences(data_splitted) #list of list
l=len(sequences)
print("Sequences:",sequences, type(sequences), l)


Sequences: [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> 4


In [ ]:
X=list()
y=list()

for i in range(len(sequences)):
  X.insert(i,sequences[i][:-1])
  y.insert(i,sequences[i])

print("X=", X, "y=",y, type(X), type(y))

maxlen = max([len(sequence) for sequence in X])
print("Maxlen:",maxlen)

#X=array(X)
#y=array(y)
#X=numpy.reshape(X,newshape=(l,-1))
#y=numpy.reshape(y,newshape=(l,-1))

X=pad_sequences(X,maxlen=maxlen+1,padding='pre') # +1 to have 0 as the first input
print("X:",X, type(X), X.shape)
y=pad_sequences(y,maxlen=maxlen+1,padding='pre')
print("y:",y, type(y), y.shape)

#z=numpy.
#for i in range(l):
#  z[i]=to_categorical(y[i],num_classes=vocab_size)

#print("X=", X, "y=",y)
y=to_categorical(y,num_classes=vocab_size)


X= [[3, 2, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14], [3, 15, 16, 2, 17, 18, 19], [2, 4, 20, 21, 22]] y= [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> <class 'list'>
Maxlen: 7
X: [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]] <class 'numpy.ndarray'> (4, 8)
y: [[ 3  2  4  5  6  7  8  1]
 [ 0  9 10 11 12 13 14  1]
 [ 3 15 16  2 17 18 19  1]
 [ 0  0  2  4 20 21 22  1]] <class 'numpy.ndarray'> (4, 8)


In [ ]:
print("X=", X, "y=",y, type(X), type(y), X.shape, y.shape)
model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10))
print(model.output_shape)
model.add(SimpleRNN(units=50, return_sequences=True))
print(model.output_shape)
model.add(Dense(units=vocab_size,activation='softmax'))
model.summary()
print("Input Shape of all Layers:",model.layers[0].input_shape,model.layers[1].input_shape,model.layers[2].input_shape)
print("Input Dim:",model.layers[0].input_dim)


X= [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]] y= [[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0

In [ ]:
model.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=['accuracy'])

model.fit(X, y, epochs=200, verbose=0)


In [ ]:
def sample_all_seq_wo_seed(model, tokenizer, n_words, vocab_size): #all the words are sampled
  encoded=list()
  in_text = ''
  # generate a fixed number of words = n_words
  for i in range(n_words):
    # encode the text as integer
    encoded = tokenizer.texts_to_sequences([in_text])[0] # for words not in the vocab it returns []
    print("i:", i, "Encoded:",encoded)
    # pre-pad sequences to a fixed length
    #encoded = pad_sequences([encoded], maxlen=max_length, padding='pre')
    encoded.insert(0,0)
    encoded=array(encoded)
    encoded=numpy.reshape(encoded,newshape=(1,-1))
    print("i:", i, "Encoded:",encoded, encoded.shape)
    # predict probability and sample a word from vocab
    if i == 0:
      prob = model.predict(encoded, verbose=0)
      print("i=", i, "Prob:", prob, type(prob), prob.shape)
      yhat=0
      while yhat == 0:
        yhat=numpy.random.choice(range(vocab_size),p=prob.ravel())
      yhat=[yhat]
      yhat=array(yhat)
      yhat=numpy.reshape(yhat,newshape=(1,-1))
      print("i:", i, "If yhat:", yhat, yhat.shape)
    else:
      prob = model.predict(encoded, verbose=0)
      print("i=", i, "Prob:", prob, type(prob), prob.shape)
      yhat=numpy.append(yhat,0)  #just creating space for the next yhat
      yhat=numpy.reshape(yhat,newshape=(1,-1))
      while yhat[0,i] == 0:
        yhat[0,i]=numpy.random.choice(range(vocab_size),p=prob[0,i].ravel())
      print("i:", i, "Else yhat:", yhat, yhat.shape)


    # map predicted word index to word
    out_word = ''
    for word, index in tokenizer.word_index.items():
      if index == yhat[0,i]:
        out_word = word
        #print("index:", index, "out_word:", out_word)
        break

    # append to input
    in_text = in_text + out_word + ' '
  return in_text

print("-----------------------sample all seq without seed-----------------------------")
print(sample_all_seq_wo_seed(model, tokenizer, 8, vocab_size))
print("-------------------------------------------------------------------------------")


def prob_of_input_sentence(model, tokenizer, sentence):
  print("Input Sentence:", sentence)
  encoded=tokenizer.texts_to_sequences([sentence])[0]
  print("encoded before insert:", encoded)
  encoded.insert(0,0)
  encoded=array(encoded)
  encoded=numpy.reshape(encoded,newshape=(1,-1))
  print("Encoded:", encoded, encoded.shape)
  prob=model.predict(encoded, verbose=0)
  print("Prob:", prob, prob.shape)
  probability=1
  for i in range(prob.shape[1]-1):
    probability = probability * prob[0,i,encoded[0,i+1]]
  print("Probability of Sentence", "\"", sentence, "\"", "is:", probability)

print("-------------------Probability of Input Sentence------------------------------")
prob_of_input_sentence(model, tokenizer, "Jack and Jill Went")
prob_of_input_sentence(model, tokenizer, "and Jill Went up")
prob_of_input_sentence(model, tokenizer, "went up the hill")
prob_of_input_sentence(model, tokenizer, "jack and Jill Went up the hill .")
prob_of_input_sentence(model, tokenizer, "to fetch a pail")
prob_of_input_sentence(model, tokenizer, "fetch a pail")
prob_of_input_sentence(model, tokenizer, "to fetch a pail of water")
prob_of_input_sentence(model, tokenizer, "jack fell down and")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke")
prob_of_input_sentence(model, tokenizer, "fell down and broke")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke his crown")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling")
prob_of_input_sentence(model, tokenizer, "jill came tumbling after")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling after .")
print("-------------------------------------------------------------------------------")


-----------------------sample all seq without seed-----------------------------
i: 0 Encoded: []
i: 0 Encoded: [[0]] (1, 1)
i= 0 Prob: [[[4.5185715e-01 2.4169188e-03 1.6604038e-02 4.6594930e-01 2.3155976e-03
   3.3587627e-03 1.4462227e-03 2.0696516e-03 1.3017289e-03 2.2116786e-02
   2.4879570e-03 6.7258778e-04 3.8083730e-04 1.0495082e-03 2.6182916e-03
   5.0713215e-03 1.8792778e-03 2.3771741e-03 2.9660871e-03 2.7564541e-03
   4.2653992e-03 2.7783606e-03 1.2606403e-03]]] <class 'numpy.ndarray'> (1, 1, 23)
i: 0 If yhat: [[3]] (1, 1)
i: 1 Encoded: [3]
i: 1 Encoded: [[0 3]] (1, 2)
i= 1 Prob: [[[4.5185727e-01 2.4169181e-03 1.6604034e-02 4.6594918e-01 2.3155969e-03
   3.3587620e-03 1.4462223e-03 2.0696511e-03 1.3017287e-03 2.2116780e-02
   2.4879563e-03 6.7258795e-04 3.8083739e-04 1.0495080e-03 2.6182896e-03
   5.0713201e-03 1.8792773e-03 2.3771734e-03 2.9660861e-03 2.7564536e-03
   4.2653983e-03 2.7783599e-03 1.2606400e-03]
  [7.9450011e-02 6.3078472e-04 3.2296872e-01 2.1836187e-03 4.760133